server:
  port: 8000

spring:
  thymeleaf:
    cache: false


mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
    type-aliases-package: com.sword.cloud.pojo           # 所有Entity别名类所在包
    mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件

spring:
   redis:
      host: 39.107.67.6
      pool:
         timeout: 50
      port: 6379
   cache:  # ehcache
      type: ehcache
      ehcache:
         config: cache/ehcache.xml

  #pagehelper分页插件
   pagehelper:
       helperDialect: mysql
       easonable: true
       supportMethodsArguments: true
       params: count=countSql
       returnPageInfo: check

   application:
    name: sword-provider-shiro
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    druid:
             filters: stat                                         #监控统计拦截的filters
             driver-class-name: com.mysql.jdbc.Driver            # mysql驱动包
             url: jdbc:mysql://39.107.67.6:3306/security?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong
             username: root
             password: sjh860811
             #配置初始化大小/最小/最大
             initial-size: 1
             min-idle: 1
             max-active: 20
             #获取连接等待超时时间
             max-wait: 60000
             #间隔多久进行一次检测，检测需要关闭的空闲连接
             time-between-eviction-runs-millis: 60000
             #一个连接在池中最小生存的时间
             min-evictable-idle-time-millis: 300000
             validation-query: SELECT 'x'
             test-while-idle: true
             test-on-borrow: false
             test-on-return: false
             #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
             pool-prepared-statements: false
             max-pool-prepared-statement-per-connection-size: 20





