server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.sword.cloud.entities           # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
   redis:
      host: 39.107.67.6
      pool:
         timeout: 50
      port: 6379
   cache:  # ehcache
      type: ehcache
      ehcache:
         config: cache/ehcache.xml


   application:
    name: sword-provider-member
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource               # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://39.107.67.6:3306/security?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Hongkong              # 数据库名称
    username: root
    password: sjh860811
    dbcp2:
      min-idle: 5                                             # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                # 等待连接获取的最大超时时间:true
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
   devtools:
     remote:
       restart:
         enabled: false

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: sword-provider-member
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: sword-provider-member-app
  company.name:  com.sword.cloud
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
logging:
  level: com.sword.cloud.dao=debug



